### ISSUE TITLE
Full width button component has radius top left and right set to 0

### ISSUE THREAD

**Issue by maciek15** [PublicInMotionGmbH/ui-kit#31]
Full width button should have all border radius set to the same value

**Comment by rangoo94** [comment]
I would prefer it with full `border-radius` as well, but for now, we should keep it this way:

<img width="1229" alt="zrzut ekranu 2018-04-03 o 10 33 15" src="https://user-images.githubusercontent.com/3843526/38238559-7c9b2522-372a-11e8-970b-1f33513a3d9e.png">
