### ISSUE TITLE
Popover - warning in console (wrong propType)

### ISSUE THREAD

**Issue by maciek15** [PublicInMotionGmbH/ui-kit#32]
There is a warning in console in storybook: Invalid prop `fade` of type `string` supplied to `Popover`, expected `boolean`

**Comment by PiotrGrzechnik** [comment]
Please see http://jira.talixo.de/browse/UI-34

**Comment by rangoo94** [comment]
@PiotrGrzechnik has updated Tooltip/Popover already so it's working correctly now.
