### ISSUE TITLE
TextInput - floating label and box-sizing

### ISSUE THREAD

**Issue by stuniel** [PublicInMotionGmbH/ui-kit#46]
Floating label in TextInput component should be an option. We should create a prop for that.

In order to prevent padding from exceeding the elements total width, TextInput should have box-sizing set to border-box.

**Comment by rangoo94** [comment]
I don’t think that it should be an option. We should keep our UI Kit consistent across all applications, so same functionality should look and work the same everywhere.

**Comment by stuniel** [comment]
@michalochman, any thoughts on that?

**Comment by michalochman** [comment]
@rangoo94 forms can have multiple variations. Some of them will have floating labels, some of them will have inline labels and other will have labels above inputs.

As an example, please have a look at how this is resolved in http://www.material-ui.com/#/components/text-field

**Comment by rangoo94** [comment]
Right now we have removed floating labels, so I think that this issue should be closed. If you have doubts, reopen it.
