### ISSUE TITLE
Label in TextInput overlays the value

### ISSUE THREAD

**Issue by stuniel** [PublicInMotionGmbH/ui-kit#48]
**Information**

* **Feature Request or Bug:** Bug
* **Components and versions affected:** TextInput 1.0.0
* **Environment:** Ubuntu 16.04, Node 8.9.4

When the input value is provided as a prop, label overlaps displayed value.

**How to reproduce?**

* go to text-input package
* open stories.js
* add `value='Some value'` prop to `TextInput` component
* in StoryBook go to TextInput
* label overlaps the value

![screenshot 5](https://user-images.githubusercontent.com/26305751/38364415-df39b20c-38d8-11e8-89cc-459cb7631703.jpeg)

**Comment by michalochman** [comment]
Also, please note that label is not vertically centered.

**Comment by rangoo94** [comment]
We do not have floating labels now, so it doesn't happen now.
