### ISSUE TITLE
Improve example of CountryFlag using custom size

### ISSUE THREAD

**Issue by michalochman** [PublicInMotionGmbH/ui-kit#69]
#### Information

- **Feature Request or Bug:** Feature Request
- **Components and versions affected:** CountryFlag 1.0.0
- **Environment:** Mac OS X 10.13.3, Node 8.9.1, 65.0.3325.181 (Official Build) (64-bit)

Please change `CountryFlag` story to not use `style={{ fontSize: X }}` directly, I think the use case would be better shown when the containing element had it's font size changed like this:
```jsx 
<p style={{ fontSize: 32 }}>We live in <CountryFlag code="pl" /> Poland</p>
```

**Comment by rangoo94** [comment]
Good point, I will fix it soon
