### ISSUE TITLE
Success Notification story is using information variant

### ISSUE THREAD

**Issue by michalochman** [PublicInMotionGmbH/ui-kit#70]
#### Information

- **Feature Request or Bug:** Bug
- **Components and versions affected:** Notifications 1.0.0
- **Environment:** Mac OS X 10.13.3, Node 8.9.1, 65.0.3325.181 (Official Build) (64-bit)

Success Notification story is using information variant, it should use success variant.

**Comment by rangoo94** [comment]
Notifications has been revisited in #119
