### ISSUE TITLE
Issues with inputs

### ISSUE THREAD

**Issue by stuniel** [PublicInMotionGmbH/ui-kit#83]
#### Information

- **Feature Request or Bug:** Bug
- **Components and versions affected:** NumberInput 1.0.0, Checkbox 1.0.0
- **Environment:** Ubuntu 16.04, Node 9.11

### NumberInput:

**1. Default component displays a car icon and 'cars' suffix.**

#### How to reproduce?

- Open stories.js.
- In StoryBook go to 'NumberInput'.

#### What is expected behavior?

- It should be displayed without icon and suffix.

**2. When `'error'` prop is passed, border doesn't change color to red.**

#### How to reproduce?

- Pass error prop to NumberInput.
- Open stories.js.
- In StoryBook go to 'NumberInput'.

#### What is expected behavior?

- Border should change color to red.

### Checkbox

**1. `onChange` returns `event` - it can return `event.target.checked`.**

#### How to reproduce?

- Pass logging function to onChange prop of Checkbox.
- Go to console.

#### What is expected behavior?

- It could return `boolean` value - checked status.

**2. It doesn't handle error.**

#### How to reproduce?

- Pass error prop to Checkbox.
- Open stories.js.
- In StoryBook go to 'Checkbox'.

#### What is expected behavior?

- Checkbox border should change color to red.

**Comment by rangoo94** [comment]
Done, revisited later in #119
